### PR TITLE
Bump the minimally support sequoia-openpgp version.

### PR DESCRIPTION
**Pull request by nwalfield**
- Bump the minimally support sequoia-openpgp version to 1.21.1.

### CODE REVIEW

**Comment by nwalfield** [comment]
@pmatilai, @dmnks: Can you please confirm that [this failure is benign](https://github.com/rpm-software-management/rpm-sequoia/actions/runs/9846230602/job/27183732102?pr=70#step:9:1545)

```
  --- -	2024-07-08 20:25:03.887142823 +0000
  +++ /home/runner/work/rpm-sequoia/rpm-sequoia/rpm-build/tests/rpmtests.dir/at-groups/273/stdout	2024-07-08 20:25:03.882178157 +0000
  @@ -1,8 +1,8 @@
  -SHA256HEADER: eb512d3d8c282d0249701032591c53ffb5904c54c95de04783028387b224d8fe
  -SHA1HEADER: a42c611d67870c1937623f0da2631eabdf33e948
  -SIGMD5: 88d1037686ed3f5f6b67618b02cc47ef
  -PAYLOADDIGEST: 116ce41ebb72f1877cda3d7dedaf5b78770e202d6389ade4e415d78548d703a8
  -PAYLOADDIGESTALT: 116ce41ebb72f1877cda3d7dedaf5b78770e202d6389ade4e415d78548d703a8
  +SHA256HEADER: 94d13620f7058c14f24605c1461a9ef89b5b50b80c421a0a0eb7f0c62fe0f638
  +SHA1HEADER: 8036a9b66aa7781e4000a441e695bb076acfc450
  +SIGMD5: 98d3343d19052974392ed389e121f4f8
  +PAYLOADDIGEST: 91438332ac8fe92e4d4fcd45edb64b659323b893d9496a339f8587d19d00531a
  +PAYLOADDIGESTALT: 91438332ac8fe92e4d4fcd45edb64b659323b893d9496a339f8587d19d00531a
   /build/RPMS/noarch/attrtest-1.0-1.noarch.rpm:
       Header SHA256 digest: OK
       Header SHA1 digest: OK
  273. rpmsigdig.at:157: 273. rpmkeys -Kv <unsigned> 2 (rpmsigdig.at:157): FAILED (rpmsigdig.at:159)
```

**Comment by dmnks** [comment]
This looks a lot like (unfixed?) https://github.com/rpm-software-management/rpm/issues/2874. Is this with rpm's master branch?

**Comment by dmnks** [comment]
Either way, this is probably some distro specifics leaking into the binary packages when they're built. We hardcode these hashes in the test suite and they're generated on Fedora. So this is most likely benign, indeed.

**Comment by nwalfield** [comment]
> This looks a lot like (unfixed?) [rpm-software-management/rpm#2874](https://github.com/rpm-software-management/rpm/issues/2874). Is this with rpm's master branch?

Ha, I forgot about that issue.  This looks like the same benign failure (different check sums on a different OS).

To answer your question: no we decided to not upgrade `rpm-sequoia`'s CI, but leave it at 4.18 on Ubuntu for now.

**Comment by dmnks** [comment]
Ack, thanks. Looking at 4.18.2, it does include the commit that was supposed to fix this (https://github.com/rpm-software-management/rpm/commit/7ec148c1d61e0b526ae5c917f0ddc2b4a3222146) so apparently it wasn't the complete fix then. That would also explain why the ticket is still open, too :smile:

**Pull request merged**
