### PR TITLE
Return NOTTRUSTED if the certificate is expired or revoke

### PR DESCRIPTION
**Pull request by nwalfield**
- When checking a signature, also return NOTTRUSTED if the certificate is expired or revoked.

  - See https://github.com/rpm-software-management/rpm/issues/2402#issuecomment-1451559925

### CODE REVIEW

**Comment by nwalfield** [comment]
@panu : Please double check, thanks!

**Comment by pmatilai** [comment]
I'll test, I just need to create some test material first...

Just to check: what do you think about this change in principle? As in, does this make sense / seem "rpm crazy" to you? :laughing: To me it seems like a nice way to handle these scenarios within the confines of rpm reality, but I may be missing some (however obvious) downsides here.

**Comment by nwalfield** [comment]
As long as NOTTRUSTED is indeed not trusted, i.e., semantically equivalent to FAILED, I think it is a great improvement in usability.  It provides the user information about why a signature isn't valid.  We could and should do even better, but the current interface is not sufficient.

**Comment by pmatilai** [comment]
Right, but it's only equivalent to FAILED for an install attempt. Query (and uninstall) of a NOTTRUSTED package (installed or otherwise) is still permitted, whereas FAILED prevents even query (and a bit paradoxically, uninstall too).

**Comment by nwalfield** [comment]
> Right, but it's only equivalent to FAILED for an install attempt. Query (and uninstall) of a NOTTRUSTED package (installed or otherwise) is still permitted, whereas FAILED prevents even query (and a bit paradoxically, uninstall too). 

Indeed, it is a bit more subtle then I thought.  Thanks for clarifying.

> But at least to me, this is exactly the desired semantics of NOTTRUSTED.

I agree that these semantics are reasonable.

**Pull request merged**
