### PR TITLE
Add _pgpVerifySignature2

### LINKED ISSUE #39: Return error messages
@panu writes:

Based on the number of new crypto related issues folks are running into on Fedora, maybe we should consider some emergency bandaid for better error messages.

Such as simply a new pgpVerifySignature() variant which has an additional char **emsg argument to return a message from the lower level. The main consumer of that is rpmKeyringVerifySig() from which we can use rpmlog() to output any error so it gets handled in dnf callbacks and stuff. Ideally the message would be returned to rpmKeyringVerifySig() instead, but then ideally this whole API would be very different so adding two more bad APIs seems worse than adding just one :D

From: https://github.com/rpm-software-management/rpm/issues/2127#issuecomment-1482646398

### PR DESCRIPTION
**Pull request by nwalfield**
- `_pgpVerifySignature2` is a variant of `_pgpVerifySignature`, which optionally returns a message either describing what wrong, or potential problems (i.e., lints).

  - Fixes #39.

### CODE REVIEW

**Comment by pmatilai** [comment]
Hey, sorry for being slow to respond, been busy scrambling with rpm 4.19 release stuff.

Testing with your rpm patch added, this seems to change NOKEY behavior. With pgpVerifySignature() from rpm-sequoia 1.3.0:

> [pmatilai🎩︎localhost brpm]$ ./rpmkeys -Kv ~/Downloads/google-chrome-stable_current_x86_64.rpm 
/home/pmatilai/Downloads/google-chrome-stable_current_x86_64.rpm:
    Header V4 DSA/SHA1 Signature, key ID 7fac5991: NOKEY
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 DSA/SHA1 Signature, key ID 7fac5991: NOKEY
    MD5 digest: OK

With this patch applied:
> /home/pmatilai/Downloads/google-chrome-stable_current_x86_64.rpm:
    Header V4 DSA/SHA1 Signature, key ID 7fac5991: BAD
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 DSA/SHA1 Signature, key ID 7fac5991: BAD
    MD5 digest: OK

With the rpm-side patch added on top:
> /home/pmatilai/Downloads/google-chrome-stable_current_x86_64.rpm:
error: Error verifying signature: Verifying a signature, but no certificate was providedPublic key is unavailable: Not provided (issuer: A040830F7FAC5991)
  error: Error verifying signature: Verifying a signature, but no certificate was providedPublic key is unavailable: Not provided (issuer: A040830F7FAC5991)
      Header V4 DSA/SHA1 Signature, key ID 7fac5991: BAD
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 DSA/SHA1 Signature, key ID 7fac5991: BAD
    MD5 digest: OK

There seems to be a newline missing from that "no certificate was provided" message.
Other than that, these messages do make a world of difference. Taking the anydesk case:

> [pmatilai🎩︎localhost brpm]$ ./rpmkeys -Kv ~/Downloads/anydesk-6.1.1-1.el8.x86_64.rpm 
/home/pmatilai/Downloads/anydesk-6.1.1-1.el8.x86_64.rpm:
error: Error verifying signature: Verifying a signature using certificate D56311E5FF3B6F39D5A16ABE18DF3741CDFFDE29:
  No binding signature at time 2021-04-13T11:08:37Z
  error: Error verifying signature: Verifying a signature using certificate D56311E5FF3B6F39D5A16ABE18DF3741CDFFDE29:
  No binding signature at time 2021-04-13T11:08:37Z
      Header V3 RSA/SHA1 Signature, key ID cdffde29: BAD
    Header SHA1 digest: OK
    V3 RSA/SHA1 Signature, key ID cdffde29: BAD
    MD5 digest: OK

With such error messages we have a fair chance of pointing out issues without asking people for hexdumps of their packages :smile:

**Comment by nwalfield** [comment]
Thanks for checking!  I'll fix those mistakes.  Can you please confirm that there are units tests for the NOTTRUSTED cases?  Thanks!

**Comment by pmatilai** [comment]
Yes there are now, just recently added in ad1bdc6520c1954d2a94fefa0a6090661f972db4.

**Comment by pmatilai** [comment]
FWIW, I'm getting multiple failures from the test-suite with this patch (without the rpm-side change). I'm building this as a patch on top of the Fedora 1.3.0 package rather than upstream rpm-sequoia git, but I don't see any changes post 1.3.0 that should affect this...

**Comment by nwalfield** [comment]
I'm investigating and I think I messed up the error codes

**Comment by nwalfield** [comment]
FYI: I don't have time to finish this today.

**Comment by pmatilai** [comment]
No worries, nobody's life is in danger because of this.

**Pull request merged**
