### PR TITLE
Better handle certificates where old self signatures are stripped

### LINKED ISSUE #46: Relax "No binding signature"
While it's great that all of this additional PGP signature/key checking is being done on F38 (and of course Fedora has completely valid keys to work with all of this additional checking) other distros are not there yet and other distros have policy-violating keys (that indeed, need to be updated).  I.e. https://bugzilla.suse.com/show_bug.cgi?id=1211022

But we still need to be able to work with those distros and their insecure keys while we wait for them to get up-to-date.  One case where this fails is trying to use [mock on F38 to build on distros that have insecure keys](https://github.com/rpm-software-management/mock/issues/1062).

We need to be able to continue to use such distros with mock on F38.

Is there a crypto-policy setting that can be relaxed to allow keys with _No binding signature_, in the meanwhile for these such cases?

### PR DESCRIPTION
**Pull request by nwalfield**
- If a certificate is not valid when a packet signature is made, but is valid now, detect this and return `NotTrusted`.  This happens when old self signatures are stripped.

  - Fixes #46

### CODE REVIEW

**Comment by pmatilai** [comment]
Regardless of what ultimately gets done about the issue with gpg stripping old self-signatures, this much seems absolutely necessary to let people upgrade away from affected packages. Such as https://bugzilla.redhat.com/show_bug.cgi?id=2215440

So my :+1: for this.

**Comment by nwalfield** [comment]
I improved the commit message, but the code is the same.

**Comment by nwalfield** [comment]
> Regardless of what ultimately gets done about the issue with gpg stripping old self-signatures, this much seems absolutely necessary to let people upgrade away from affected packages. Such as https://bugzilla.redhat.com/show_bug.cgi?id=2215440
> 
> So my +1 for this.

Thanks for the feedback.

**Comment by nwalfield** [comment]
I can do a release today.

**Comment by pmatilai** [comment]
Awesome, thanks!

**Pull request merged**
